### ISSUE TITLE
Some help with the unnamed classes

### ISSUE THREAD

**Issue by ThePixelGamer** [HerryYT/MinecraftPE-0.1.3#5]
b is a Runnable class
https://docs.oracle.com/javase/7/docs/api/java/lang/Runnable.html#:~:text=A%20class%20that%20implements%20Runnable,and%20no%20other%20Thread%20methods.

function a (classes d-f) in MainActivity looks something like this - some of the extra code from a newer version
![image](https://user-images.githubusercontent.com/15077848/217969032-8f90fe14-3f13-45b2-a0cc-f91fe7c52bd6.png)

unsure about class g as it doesn't seem to be present in the version I'm looking at

**Comment by MFDGaming** [comment]
Many of the names are known from the 0.1.0-touch build

**Comment by ThePixelGamer** [comment]
Which 0.1.3 build did you copy the java code from?

**Comment by MFDGaming** [comment]
> Which 0.1.3 build did you copy the java code from?

0.1.3j arm

**Comment by ThePixelGamer** [comment]
Interesting, I was taking a look at that one the other day and it seems to have some extra classes that are missing from the repo, unless they're automatically generated? Also I'm not entirely sure how they handled it but some classes aren't present in some of the builds
